### GET ALL
GET http://localhost:1234/api/users

### GET BY ID
GET http://localhost:1234/api/users/ca0158bb-8cc4-11ee-8bb3-5c879cd6d846

### CREATE
POST http://localhost:1234/api/users
Content-Type: application/json

{
  "name":"pablo",
  "gmail": "pablo@gmail.com",
  "password": "12345678"
}

### UPDATE
PATCH http://localhost:1234/api/users/ca0158bb-8cc4-11ee-8bb3-
Content-Type: application/json

{
  "name":"maria",
  "gmail": "1234@gmail.com",
  "password": "12345678"
}

### DELETE
DELETE http://localhost:1234/api/users/6569ec0aacc29a5d91043d48